//测试数据
var data=[
    {
      name:"巨头",
      content:[{
        pic:'../images/shouye1.jpg',
        title:'出海 | 蓝领＋东南亚=新风口？GrabJobs要切东南亚蓝领招聘',
        content:'6 亿人口， 1 亿蓝领，东南亚蓝领招聘要怎么玩？',
        writer:'宗地',
        time:'19:35',
        read:'阅读(276)',
        share:'分享'
      },{
        pic:'../images/shouye2.jpg',
        title:'亚马逊正开发 AFC 航空物流中心，用无人机送货上门',
        content:'以后，取快递再也不用到现场了，包裹会从空中掉下来。',
        writer:'bnjhj',
        time:'两小时前',
        read:'阅读(276)',
        share:'分享'
      },{
        pic:'../images/shouye3.jpg',
        title:'阿里CEO谈新零售：懂货的百货公司没几个，人货场的关系要重构',
        content:'马云提出了包括“新零售”在内的“五新”，宗庆后却说“除了新技术以外，其他都是胡说八道”。透过阿里CEO张勇的演讲，一起看看是不是在胡说八道。',
        writer:'零售老板内参',
        time:'17小时前',
        read:'阅读(276)',
        share:'分享'
      },{
        pic:'../images/shouye4.jpg',
        title:'划定停车位、地铁口禁停，共享单车的监管政策会越来越多？',
        content:'除了划定专门的停车位，多地还出台了更为详细的停放规定。',
        writer:'宗地',
        time:'19:35',
        read:'阅读(276)',
        share:'分享'
      },{
        pic:'../images/shouye5.jpg',
        title:'国资助力媒体转型：东方早报休刊，澎湃新闻融资6.1亿',
        content:'纸媒的停刊潮，或许才刚刚开始。',
        writer:'高小倩',
        time:'19:35',
        read:'阅读(276)',
        share:'分享'
      },{
        pic:'../images/shouye6.jpg',
        title:'OPPO花15亿在印度建厂，国产手机纷纷入局，三星还能保住第一的位置吗？',
        content:'华为定下“明年夺取10%市场份额”的大目标。？',
        writer:'宗地',
        time:'19:35',
        read:'阅读(276)',
        share:'分享'
      },{
        pic:'../images/shouye7.jpg',
        title:'“性冷淡”的微信小程序与张小龙的野心——评张小龙的小程序10答',
        content:'按照张小龙的说法，微信小程序在正式开放以后，将不会提供大量的“入口”和“导流”功能，这几乎在很多看起来是某种“性冷淡”式的做法。',
        writer:'宗地',
        time:'19:35',
        read:'阅读(276)',
        share:'分享'
      },{
        pic:'../images/shouye8.jpg',
        title:'2016微信数据报告：日登录用户达到7.68亿，50%用户使用时长达90分钟',
        content:'除夕当日，红包发送次数达到23.5亿次。',
        writer:'宗地',
        time:'19:35',
        read:'阅读(276)',
        share:'分享'
      },{
        pic:'../images/shouye9.jpg',
        title:'从“ 10 亿美元”到 2 亿美元之后，豌豆荚已去，轻芒重生',
        content:'别了，豌豆荚；你好，轻芒',
        writer:'冉浩',
        time:'19:35',
        read:'阅读(276)',
        share:'分享'
      }],
      writers:[
        {
          name:'张平',
          photo:'../images/guanggao_sub1.jpg',
          detail:'资深互联网从业者'
        },
        {
          name:'张平',
          photo:'../images/guanggao_sub1.jpg',
          detail:'新锐作者'
        },
        {
          name:'张平',
          photo:'../images/guanggao_sub1.jpg',
          detail:'资深互联网从业者'
        },
        {
          name:'张平',
          photo:'../images/guanggao_sub1.jpg',
          detail:'资深互联网从业者'
        },
        {
          name:'张平',
          photo:'../images/guanggao_sub1.jpg',
          detail:'资深互联网从业者'
        },
        {
          name:'张平',
          photo:'../images/guanggao_sub1.jpg',
          detail:'资深互联网从业者'
        },
        {
          name:'张平',
          photo:'../images/guanggao_sub1.jpg',
          detail:'资深互联网从业者'
        },
        {
          name:'张平',
          photo:'../images/guanggao_sub1.jpg',
          detail:'资深互联网从业者'
        },
        {
          name:'张平',
          photo:'../images/guanggao_sub1.jpg',
          detail:'资深互联网从业者'
        },
        {
          name:'张平',
          photo:'../images/guanggao_sub1.jpg',
          detail:'资深互联网从业者'
        }
      ],
      ranking:{
        day:[
          {
            title:'这是标题第一名',
            content:'这是内容'
          }
        ],
        week:[
          {
            title:'27岁的他，凭什么打脸乔布斯、叫板马斯克？',
            content:'这是内容'
          }
        ] 

        } 
    },
    {
      name:"人物",
      content:[{
        pic:'../images/renwu1.jpg',
        title:'27岁的他，凭什么打脸乔布斯、叫板马斯克？',
        content:'看似毫不相关的三件事背后，却站着同一个人——乔治·霍兹，今年 27 岁，却已经是世界上最顶级的黑客。',
        writer:'即可世界',
        time:'19:35',
        read:'阅读(23)',
        share:'分享'
      },{
        pic:'../images/renwu2.jpg',
        title:'“五新”被炮轰，是马云胡说还是董明珠们老了？',
        content:'在企业发展到现在这个节骨眼上，董大姐和宗庆后走向了两个极端，一个向左一个向右，董大姐是表面的激进派而宗庆后则是从里到外的保守派。',
        writer:'前网易科技记者张钧泓',
        time:'19:35',
        read:'阅读(23)',
        share:'分享'
      },{
        pic:'../images/renwu3.jpg',
        title:'董小姐炮轰马云”五新“，但殊不知拥抱才有未来',
        content:'在央视财经频道播出的新一期《对话》节目中，实体经济企业家代表集体攻击了马云提出的“五新”观点。',
        writer:'果仁',
        time:'19:35',
        read:'阅读(23)',
        share:'分享'
      },{
        pic:'../images/renwu4.jpg',
        title:'重磅！张小龙首次阐述小程序，与公众号可以互相跳',
        content:'我理解，未来的应用程序应该是一种无处不在，随时可以访问的状态。小程序最基础的特性是无需安装，第二点是触手可及，第三点是用完即走，它是一种更加灵活的形态。',
        writer:'果仁',
        time:'19:35',
        read:'阅读(23)',
        share:'分享'
      },{
        pic:'../images/renwu5.jpg',
        title:'2017微信公开课PRO版｜张小龙演讲干货',
        content:'在今天的微信公开课广州PRO版上，“微信之父”张小龙宣布：希望小程序1月9日正式上线！',
        writer:'果仁',
        time:'19:35',
        read:'阅读(23)',
        share:'分享'
      },{
        pic:'../images/renwu6.jpg',
        title:'2016十大科技人物：谁被捧杀谁被低估',
        content:'2016年，他们霸占了头条。',
        writer:'果仁',
        time:'19:35',
        read:'阅读(23)',
        share:'分享'
      },{
        pic:'../images/renwu7.jpg',
        title:'离开搜房重新创业，他要帮有钱人海外买房',
        content:'据胡润研究院调查数据显示，截止2016年5月份，中国大陆地区总资产千万以上的高净值人群数量约为134万，可投资资产千万以上的人群数量约68.3万。',
        writer:'果仁',
        time:'19:35',
        read:'阅读(23)',
        share:'分享'
      },{
        pic:'../images/renwu8.jpg',
        title:'不仅是融了1.4亿，他的AA ROOM或改写酒店行业格局',
        content:'探索单体经济型酒店的出路',
        writer:'果仁',
        time:'19:35',
        read:'阅读(23)',
        share:'分享'
      },{
        pic:'../images/renwu9.jpg',
        title:'为什么研发人最该关注专利？',
        content:'为什么研发人最该关注专利？',
        writer:'智慧牙',
        time:'19:35',
        read:'阅读(23)',
        share:'分享'
      }],
      writers:[
        {
          name:'张平',
          photo:'../images/guanggao_sub1.jpg',
          detail:'资深互联网从业者'
        }
      ],
      ranking:{
        day:[
          {
            title:'这是标题第一名',
            content:'这是内容'
          }
        ],
        week:[
          {
            title:'这是标题第一名',
            content:'这是内容'
          }
        ] 
        } 
    },
    {
      name:"电商",
      content:[{
        pic:'../images/dianshang1.jpg',
        title:'天猫和美的100亿打脸宗庆后、董明珠“五新胡说论”',
        content:'热闹看完呛声听完，可以给点掌声……',
        writer:'举个例子',
        time:'19:35',
        read:'阅读(23)',
        share:'分享'
      },{
        pic:'../images/dianshang2.jpg',
        title:'炮轰马云后 董明珠却被美的100亿惊呆',
        content:'个人感觉，就算董小姐再不爽马云、雷军等大佬，最后也会在企业的利益和销售利润的现实前妥协，唯一期待的只是时间早晚，或者是否来得及的选择题了。',
        writer:'杨建',
        time:'19:35',
        read:'阅读(23)',
        share:'分享'
      },{
        pic:'../images/dianshang3.jpg',
        title:'华药电商年终订货会三地联动 布局全国市场',
        content:'2016年12月27日，年末规模最为宏大的订货会——华药电商年终系列线上订货会，在长沙、沈阳、扬州三城同时打响',
        writer:'果仁',
        time:'19:35',
        read:'阅读(23)',
        share:'分享'
      },{
        pic:'../images/dianshang4.jpg',
        title:'2016年度盘点，京东都发生了哪些惊人的变化',
        content:'过去一年，在资本寒冬中，整个电商行业都发生了巨大的变化，大量中小电商和O2O创业公司倒闭，但阿里京东等巨头们依然在高歌猛进。东哥做一下深度盘点和解读，通过京东业务来判断未来电商趋势。',
        writer:'果仁',
        time:'19:35',
        read:'阅读(23)',
        share:'分享'
      },{
        pic:'../images/dianshang5.jpg',
        title:'被忽视的千亿级市场，情趣产业该如何掘金？',
        content:'随着新一代消费者的成长，加情趣用品电商的崛起，情趣用品行业已经出现了品牌化的趋势，并有望成为下一个千亿规模的朝阳产业。',
        writer:'果仁',
        time:'19:35',
        read:'阅读(23)',
        share:'分享'
      }],
      writers:[
        {
          name:'张平',
          photo:'../images/guanggao_sub1.jpg',
          detail:'资深互联网从业者'
        }
      ],
      ranking:{
        day:[
          {
            title:'这是标题第一名',
            content:'这是内容'
          }
        ],
        week:[
          {
            title:'这是标题第一名',
            content:'这是内容'
          }
        ]  
        }
    },
    {
      name:"创投",
      content:[{
        pic:'../images/chuangtou1.jpg',
        title:'FMC完成Pre-A轮融资，和谐汽车出资3000万美元',
        content:'值得注意的是，FMC的初创管理团队中共有十几位高管以个人名义投资入股。',
        writer:'果仁',
        time:'19:35',
        read:'阅读(23)',
        share:'分享'
      },{
        pic:'../images/chuangtou2.jpg',
        title:'备战2017年第一个非农周 ：非农让财富奔跑',
        content:'上兵伐谋，不战而屈人之兵',
        writer:'果仁',
        time:'19:35',
        read:'阅读(23)',
        share:'分享'
      },{
        pic:'../images/chuangtou3.jpg',
        title:'九成大学生有创业意向 天津“就业即落户”增新据点',
        content:'只知道现在的90后有想法，没想到中国人民大学的一次调查显示，居然有超过9成的大学生有创业意向，实际创业的比例呢，也应该远大于前几年',
        writer:'果仁',
        time:'19:35',
        read:'阅读(23)',
        share:'分享'
      },{
        pic:'../images/chuangtou4.jpg',
        title:'初创企业如何做品牌？⑦品牌必须是“创始人工程”',
        content:'创业企业的品牌形象就是，创业企业所有行为的集合：你不是你所想的，你是你所做的。',
        writer:'果仁',
        time:'19:35',
        read:'阅读(23)',
        share:'分享'
      },{
        pic:'../images/chuangtou5.jpg',
        title:'创头条联合科创通发布首个成都双创地图',
        content:'12月28日，在成都市创新创业载体2016年度工作总结会上，创投资讯平台和创业服务机构创头条（ctoutiao.com）联合“科创通——成都创新创业服务平台”，发布了首个成都双创地图。',
        writer:'果仁',
        time:'19:35',
        read:'阅读(23)',
        share:'分享'
      },],
      writers:[
        {
          name:'张平',
          photo:'../images/guanggao_sub1.jpg',
          detail:'资深互联网从业者'
        }
      ],
      ranking:{
        day:[
          {
            title:'这是标题第一名',
            content:'这是内容'
          }
        ],
        week:[
          {
            title:'这是标题第一名',
            content:'这是内容'
          }
        ]  
        }
    },
    {
      name:"智能硬件",
      content:[{
        pic:'../images/yingjian1.jpg',
        title:'华为P9销量破千万，工业设计能否开国产手机分水岭？',
        content:'华为P9依靠什么样的设计实现了销量破千万？',
        writer:'果仁',
        time:'19:35',
        read:'阅读(23)',
        share:'分享'
      },{
        pic:'../images/yingjian2.jpg',
        title:'独家发布！亚马逊中国2016智能产品数据及2017年趋势',
        content:'三个Top10榜单：2016「智能产品」购买力城市榜Tpo10、最受欢迎品牌Top10、最受欢迎产品Top10',
        writer:'果仁',
        time:'19:35',
        read:'阅读(23)',
        share:'分享'
      },{
        pic:'../images/yingjian3.jpg',
        title:'海尔破解百年洗澡安全难题，颠覆热水器行业格局',
        content:'“洗澡安全”是热水器企业亟需解决的用户“痛点”，也是热水器企业快速引领的“风口”，海尔是如何解决这一难题的？？',
        writer:'果仁',
        time:'19:35',
        read:'阅读(23)',
        share:'分享'
      },{
        pic:'../images/yingjian4.jpg',
        title:'VR遇冷？踩过供应链大坑后，他为何被徐小平看好',
        content:'「坦率讲，我们在创业前并没有考虑后来VR会如此火热，事实上我们去做的VR和目前市面上流行的VR眼镜也大不相同。」驰疆科技的联合创始人杜耀坤告诉《接招》。',
        writer:'果仁',
        time:'19:35',
        read:'阅读(23)',
        share:'分享'
      },{
        pic:'../images/yingjian5.jpg',
        title:'众筹排行榜：这个杯子让你心甘情愿每天喝八杯水？',
        content:'Geek君每天为您选取最重要的众筹信息',
        writer:'Geek',
        time:'19:35',
        read:'阅读(23)',
        share:'分享'
      }],
      writers:[
        {
          name:'李四',
          photo:'../images/guanggao_sub1.jpg',
          detail:'资深互联网从业者'
        }
      ],
     ranking:{
        day:[
          {
            title:'这是标题第一名',
            content:'这是内容'
          }
        ],
        week:[
          {
            title:'这是标题第一名',
            content:'这是内容'
          }
        ] 
        } 
    },
        {
      name:"互联网+",
      content:[{
        pic:'../images/hulianwang1.jpg',
        title:'不用再猜了，乐视汽车莫干山项目今天正式开工',
        content:'就在乐视造车处于巨大争议之中时，今天，乐视汽车莫干山项目正式开工了。',
        writer:'果仁',
        time:'19:35',
        read:'阅读(23)',
        share:'分享'
      },{
        pic:'../images/hulianwang2.jpg',
        title:'2016 年，有哪些值得我们铭记的「汽车科技配置」？',
        content:'年底了，是时候来一波盘点了，这篇文章我们来聊聊「科技配置」。有资格入选这篇文章的科技配置，起码应该具备两个属性：一是 2016 年发布并量产，二是创新性。',
        writer:'果仁',
        time:'19:35',
        read:'阅读(23)',
        share:'分享'
      },{
        pic:'../images/hulianwang3.jpg',
        title:'2016汽车行业“神评论”，我只服这十条',
        content:'某种意义上，绕开那些语不惊人死不休的话语，才能更好的理解这些“声音”。',
        writer:'果仁',
        time:'19:35',
        read:'阅读(23)',
        share:'分享'
      },{
        pic:'../images/hulianwang4.jpg',
        title:'2016中国汽车业的“决定性瞬间”，你猜出几个？',
        content:'十个瞬间，记录2016中国车市的喜怒哀乐。',
        writer:'果仁',
        time:'19:35',
        read:'阅读(23)',
        share:'分享'
      },{
        pic:'../images/hulianwang5.jpg',
        title:'为什么说我们都是“公众号媒体人”？',
        content:'一张图带你看懂媒介发展史',
        writer:'果仁',
        time:'19:35',
        read:'阅读(23)',
        share:'分享'
      },],
      writers:[
        {
          name:'李四',
          photo:'../images/guanggao_sub1.jpg',
          detail:'资深互联网从业者'
        }
      ],
     ranking:{
        day:[
          {
            title:'这是标题第一名',
            content:'这是内容'
          }
        ],
        week:[
          {
            title:'这是标题第一名',
            content:'这是内容'
          }
        ] 
        } 
    },
    {
      name:"P2P",
      content:[{
        pic:'../images/p2p1.jpg',
        title:'“全国首例网贷评级不正当竞争案”一审判决的两遗憾',
        content:'P2P或网贷行业从业者，是否适合发布行业从业者评级报告？其给有竞争关系的网贷平台发布较低评价或“差评”，是否有不正当竞争之嫌？',
        writer:'果仁',
        time:'19:35',
        read:'阅读(23)',
        share:'分享'
      },{
        pic:'../images/p2p2.jpg',
        title:'重磅 | 红途网贷可持续发展能力评审总榜单火热出炉',
        content:'重磅 | 红途网贷可持续发展能力评审总榜单火热出炉',
        writer:'果仁',
        time:'19:35',
        read:'阅读(23)',
        share:'分享'
      },{
        pic:'../images/p2p3.jpg',
        title:'苏宁金融研究院发布《2016年江苏网贷行业发展报告》',
        content:'所谓一叶知秋，从对江苏网贷行业的解析中，依稀可以看到整个行业在2016年的转型与突围',
        writer:'果仁',
        time:'19:35',
        read:'阅读(23)',
        share:'分享'
      },{
        pic:'../images/p2p4.jpg',
        title:'智能清收会是互联网金融下一个独角兽？',
        content:'经济低迷之下，如何寻找机会。',
        writer:'果仁',
        time:'19:35',
        read:'阅读(23)',
        share:'分享'
      },{
        pic:'../images/p2p5.jpg',
        title:'“网贷评级第一案”正式宣判，有几个问题需要厘清',
        content:'对于网贷评级，投资人究竟在期待什么？',
        writer:'果仁',
        time:'19:35',
        read:'阅读(23)',
        share:'分享'
      }],
      writers:[
        {
          name:'张平',
          photo:'../images/guanggao_sub1.jpg',
          detail:'资深互联网从业者'
        }
      ],
      ranking:{
        day:[
          {
            title:'这是标题第一名',
            content:'这是内容'
          }
        ],
        week:[
          {
            title:'这是标题第一名',
            content:'这是内容'
          }
        ] 
        } 
    },
    {
      name:"前缘技术",
      content:[{
        pic:'../images/hightech1.jpg',
        title:'2016年十大科技突破',
        content:'前沿科技是物化新装备、形成新能力的“孵化器”，超前谋划和抢先占领前沿技术制高点，是武器装备创新突破的重要途径。',
        writer:'果仁',
        time:'19:35',
        read:'阅读(23)',
        share:'分享'
      },{
        pic:'../images/hightech2.jpg',
        title:'这项未来能治愈癌症的技术可能引发席卷全人类的冲突',
        content:'没有什么创新堪与基因编辑比肩。',
        writer:'果仁',
        time:'19:35',
        read:'阅读(23)',
        share:'分享'
      },{
        pic:'../images/hightech3.jpg',
        title:'VR三条：[深度]是什么驱使我们探寻沉浸式体验',
        content:'1、[深度]是什么驱使我们探寻沉浸式体验； 2、小岛秀夫：VR 将彻底改变娱乐、教育和文化； 3、新版恐龙战队将增加 VR 体验 你将亲自驾驶佐德号机器人',
        writer:'果仁',
        time:'19:35',
        read:'阅读(23)',
        share:'分享'
      },{
        pic:'../images/hightech4.jpg',
        title:'亿航们的仓库还得靠父母看，高管解决不了',
        content:'由于公司没有完善成熟的产品链，也没有有说服力的销售渠道，只能靠采购来向外刷脸索要优先合作。这使得采购在实业公司占有极大的地位，吃回扣情况频频发生。所以采购一般由公司合伙人担任，以保证稳定发展。',
        writer:'果仁',
        time:'19:35',
        read:'阅读(23)',
        share:'分享'
      },{
        pic:'../images/hightech5.jpg',
        title:'人民财经高峰论坛：把好财经直播门',
        content:'新的市场参与者强调的是具有较强的和催生高技术产业的物质能力，技术创新政策和环境的创造者和维护者',
        writer:'果仁',
        time:'19:35',
        read:'阅读(23)',
        share:'分享'
      },],
      writers:[
        {
          name:'张平',
          photo:'../images/guanggao_sub1.jpg',
          detail:'资深互联网从业者'
        }
      ],
     ranking:{
        day:[
          {
            title:'这是标题第一名',
            content:'这是内容'
          }
        ],
        week:[
          {
            title:'这是标题第一名',
            content:'这是内容'
          }
        ]  
        }
    },
     {
      name:"游戏",
      content:[{
        pic:'../images/game1.jpg',
        title:'2016年十款最佳创意休闲游戏：做别人想不到的游戏',
        content:'A单机和多人在线即时对战模式都很魔性，分分钟停不下来。',
        writer:'果仁',
        time:'19:35',
        read:'阅读(23)',
        share:'分享'
      },{
        pic:'../images/game2.jpg',
        title:'8个月盈利2.8亿，闲徕互娱是“造富神话”？',
        content:'成立8个月，盈利2.8亿，地方性棋牌厂商闲徕互娱是“造富神话”还是“资本工具”？',
        writer:'果仁',
        time:'19:35',
        read:'阅读(23)',
        share:'分享'
      },{
        pic:'../images/game3.jpg',
        title:'腾讯网易暴雪任天堂，游戏巨头们都在泛娱乐了',
        content:'2016年的游戏IP泛娱乐大事件，以及一些数据表现。 | 三文娱年度盘点③',
        writer:'果仁',
        time:'19:35',
        read:'阅读(23)',
        share:'分享'
      },{
        pic:'../images/game4.jpg',
        title:'晨游CEO熊振： 从商业角度出发决定游戏类型选择',
        content:'现在每个平台的量都不大，这要求我们有一个对收入理性的预估，产品定价从研究竞品开始。。',
        writer:'果仁',
        time:'19:35',
        read:'阅读(23)',
        share:'分享'
      },{
        pic:'../images/game5.jpg',
        title:'五大基因13款新游 网易公布2017年新游战略计划',
        content:'2016年12月27日，网易“热爱至上”游戏热爱者年度盛典在上海世博创意秀场火热展开。',
        writer:'果仁',
        time:'19:35',
        read:'阅读(23)',
        share:'分享'
      },],
      writers:[
        {
          name:'张平',
          photo:'../images/guanggao_sub1.jpg',
          detail:'资深互联网从业者'
        }
      ],
      ranking:{
          day:[
            {
              title:'这是标题第一名',
              content:'这是内容'
            }
          ],
          week:[
            {
              title:'这是标题第一名',
              content:'这是内容'
            }
          ]
      }
    }
];
